const BACKGROUND_COLOR_BLACK = '#0F0F0F';
const BACKGROUND_COLOR_DARKGRAY = '#1B1A20';
const BACKGROUND_COLOR_GRAY = '#29292F';

export {
  BACKGROUND_COLOR_BLACK,
  BACKGROUND_COLOR_DARKGRAY,
  BACKGROUND_COLOR_GRAY,
};
